In [181]:
import numpy as np
import pandas as pd
# import matplotlib as mpl
# import seaborn as sbs

y = np.random.randint(1,5,5)
y
coloumn = ['sl_no','acount_no','pin','ifsc','address','plot_no','pan_no','vter_no','school','college','stream','medical history','dob','profession','contact no','adiction']
len(coloumn)
sl_no = np.linspace(1,100,100,np.int64)
acount_no = np.random.normal(500000000,200000000,5000)
acount_no = np.int64(acount_no)
a = np.random.randint(1,100,2700)
a
for i in a:
    acount_no[i] = 000000000
acount_no



array([ 826228667,          0,          0, ..., -149224017,  556883175,
        482735794])

In [180]:
pin = np.random.normal(5000,2000,5000)
pin = np.int64(pin)
b = np.random.randint(1,100,4600)
b
for i in b:
    pin[i] = 000000000
pin

array([7133,    0,    0, ..., 3413, 6112, 4479])

In [183]:
rifsc = np.random.randint(000000,999999,20)
ifsc = np.zeros(5000,np.int64)
ifsc
c = np.random.randint(1,5000,2000)
for i in c:
    if i>19:
        j = np.random.randint(0,20)
    else:
        j = i
    ifsc[i] = rifsc[j]
ifsc

array([     0, 903353,      0, ...,      0,      0,      0])

In [184]:
acount_no = pd.Series(acount_no)
pin = pd.Series(pin)
frame = {'acount_no':acount_no,'pin':pin,'ifsc':ifsc}
data = pd.DataFrame(frame)
data
data.to_excel("sample_data.xlsx")

In [76]:
address = {'1':'west','2':'south','3':'north','4':'east','5':'north_east','6':'north_west','7':'south_east','8':'south_west'}
address

{'1': 'west',
 '2': 'south',
 '3': 'north',
 '4': 'east',
 '5': 'north_east',
 '6': 'north_west',
 '7': 'south_east',
 '8': 'south_west'}

In [77]:
addresss = np.random.normal(4.5,1.5,8)
addresss = np.int64(addresss)
addresss


array([4, 4, 2, 3, 4, 3, 1, 2])

In [185]:
ad = np.zeros(5000,np.int64)
ad
no = 3750
i = 0
while i<no:
    ad[np.random.randint(0,5000)] = addresss[np.random.randint(0,7)]
    i+=1
ad

array([0, 2, 3, ..., 0, 4, 4])

In [186]:
l = []
for i in ad:
    if i == 0:
        l.append(0)
    else:
        l.append(address[str(i)])
l
# address['1']
location = pd.Series(l)
location


0           0
1       south
2       north
3           0
4        east
        ...  
4995    south
4996     west
4997        0
4998     east
4999     east
Length: 5000, dtype: object

In [187]:
data['location'] = location
data.to_excel("sampledata2.xlsx")
data

acount_no   pin    ifsc location
0     826228667  7133       0        0
1             0     0  903353    south
2             0     0       0    north
3             0     0   36476        0
4             0     0       0     east
...         ...   ...     ...      ...
4995  510396661  5025  350705    south
4996  655034787  4448  350705     west
4997 -149224017  3413       0        0
4998  556883175  6112       0     east
4999  482735794  4479       0     east

[5000 rows x 4 columns]

In [188]:
#pan
import random as r
alphabet = ['a','b','c','d','e','f']
# a = 
num = np.random.randint(10000,99999,5000)
num
pan = []
for i in range(5000):
    x = np.random.randint(0,5)
    y = np.random.randint(0,5)
    trans = alphabet[x]+alphabet[y]+str(num[i])
    pan.append(trans)
pan
# x = np.random.randint(0,5)
# x
pan = pd.Series(pan)
data['pan'] = pan
data.head()

acount_no   pin    ifsc location      pan
0  826228667  7133       0        0  bb88797
1          0     0  903353    south  cb81787
2          0     0       0    north  eb24903
3          0     0   36476        0  ce40527
4          0     0       0     east  eb42543

In [189]:
#voter
import random as r
alphabet1 = ['a','b','c','d','e','f']
alphabet2 = ['e','f','g','h','i','j','x']
# a = 
num = np.random.randint(1000000,9999999,5000)
num
voter = []
for i in range(5000):
    x = np.random.randint(0,5)
    y = np.random.randint(0,5)
    trans = alphabet1[x]+str(num[i])+alphabet2[y]
    voter.append(trans)
voter
# x = np.random.randint(0,5)
# x
voter = pd.Series(voter)
data['voter'] = voter
data.head()

acount_no   pin    ifsc location      pan      voter
0  826228667  7133       0        0  bb88797  d4464454h
1          0     0  903353    south  cb81787  a8778367h
2          0     0       0    north  eb24903  b3645292e
3          0     0   36476        0  ce40527  c5023709g
4          0     0       0     east  eb42543  b7747576g

In [192]:
sch = ['D.A.V public school, asansol',
'D.A.V public school, Durgapur',
'Hemsheela Public School, Durgapur',
'Loreto convent school',
'La Martine boys school',
'Ramkrishna mission, Asansol',
'Delhi public school',
'Indira Gandhi girls school, Delhi',
'Dhirubhai ambani public school, Mumbai',
'St. Vincents school',
'St. Patricks school',
' Burnpur Riverside School, Burnpur',
' North point public school,Chanda',
 'Uma Rani gorai mohila Kalyan, Asansol',
 'national gems higher secondary school, Kolkata' 'AG Church , Sodepoore',
 'guru govind Singh public school, Chandigarh',
 'Narayan group of schools, asansol',
 'La Martine Boys, Kolkata',
'army school , shiliguri']
school = []
for i in range(5000):
    school.append(sch[np.random.randint(0,len(sch))])
school
school = pd.Series(school)
data['school'] = school
data

acount_no   pin    ifsc location      pan      voter  \
0     826228667  7133       0        0  bb88797  d4464454h   
1             0     0  903353    south  cb81787  a8778367h   
2             0     0       0    north  eb24903  b3645292e   
3             0     0   36476        0  ce40527  c5023709g   
4             0     0       0     east  eb42543  b7747576g   
...         ...   ...     ...      ...      ...        ...   
4995  510396661  5025  350705    south  ec33134  e8042107g   
4996  655034787  4448  350705     west  de77200  b5139369f   
4997 -149224017  3413       0        0  ac92486  e1207693f   
4998  556883175  6112       0     east  ad39057  b9659638i   
4999  482735794  4479       0     east  bd89211  b2330781h   

                                                 school  
0                           Ramkrishna mission, Asansol  
1     national gems higher secondary school, Kolkata...  
2                          D.A.V public school, asansol  
3                     Hemsheela Public School, Durgapur  
4                      North point public school,Chanda  
...                                                 ...  
4995  national gems higher secondary school, Kolkata...  
4996                       D.A.V public school, asansol  
4997                             La Martine boys school  
4998        guru govind Singh public school, Chandigarh  
4999                           La Martine Boys, Kolkata  

[5000 rows x 7 columns]

In [195]:

med = ['analgesics',
'antacids',
'antianxiety drugs',
'antiarrhythmics',
'antibacterial',
 'antibiotics',
'anticoagulant',
'thrombolytic',
'anticonvulsant',
' antidepressants',
 'antidiarrheals',
' antiemetics',
 'antifungals',
'antihypertensives',
 'anti-inflammatory',
 'antineoplastic',
 'antipsychotics',
 'antipyretics',
'antivirals',
 'barbiturates',
'beta-blockers',
 'bronchodilators',
'cold cures',
 'corticosteroids',
'cough suppressants',
 'cytotoxics',
 'decongestants',
 'diuretics',
 'expectorant',
'hormones',
'hypoglycemics',
'immunosuppressives',
'laxatives',
 'muscle relaxants',
'sedatives',
'sex hormones',
 'sleeping drugs',
'tranquilizer',
 'vitamins',]
med
medicine_group = []
for i in range(5000):
    medicine_group.append(med[np.random.randint(0,len(med))])
z = np.random.randint(0,5000,3000)
for i in z:
    medicine_group[i] = 0
    
medicine_group = pd.Series(medicine_group)

data['medicine_group'] = medicine_group
data

acount_no   pin    ifsc location      pan      voter  \
0     826228667  7133       0        0  bb88797  d4464454h   
1             0     0  903353    south  cb81787  a8778367h   
2             0     0       0    north  eb24903  b3645292e   
3             0     0   36476        0  ce40527  c5023709g   
4             0     0       0     east  eb42543  b7747576g   
...         ...   ...     ...      ...      ...        ...   
4995  510396661  5025  350705    south  ec33134  e8042107g   
4996  655034787  4448  350705     west  de77200  b5139369f   
4997 -149224017  3413       0        0  ac92486  e1207693f   
4998  556883175  6112       0     east  ad39057  b9659638i   
4999  482735794  4479       0     east  bd89211  b2330781h   

                                                 school     medicine_group  
0                           Ramkrishna mission, Asansol                  0  
1     national gems higher secondary school, Kolkata...                  0  
2                          D.A.V public school, asansol                  0  
3                     Hemsheela Public School, Durgapur  antihypertensives  
4                      North point public school,Chanda                  0  
...                                                 ...                ...  
4995  national gems higher secondary school, Kolkata...       barbiturates  
4996                       D.A.V public school, asansol                  0  
4997                             La Martine boys school                  0  
4998        guru govind Singh public school, Chandigarh         cold cures  
4999                           La Martine Boys, Kolkata                  0  

[5000 rows x 8 columns]

In [196]:
# dob
date = []
for i in range(5000):
    d = np.random.randint(1,31)
    m = np.random.randint(1,12)
    y = np.random.randint(1950,2000)
    date.append(str(d)+':'+str(m)+':'+str(y))
z = np.random.randint(0,5000,1790)
for i in z:
    date[i] = 0
dateofbirth = pd.Series(date)
data['date_of_birth'] = dateofbirth
data.head(20)

acount_no   pin    ifsc location      pan      voter  \
0   826228667  7133       0        0  bb88797  d4464454h   
1           0     0  903353    south  cb81787  a8778367h   
2           0     0       0    north  eb24903  b3645292e   
3           0     0   36476        0  ce40527  c5023709g   
4           0     0       0     east  eb42543  b7747576g   
5           0     0       0     east  ac68715  d1538336h   
6           0     0       0    north  ae82711  e3807922e   
7           0     0       0     east  ed36695  c3964407g   
8           0     0       0    south  ba52417  e4785474h   
9           0     0       0        0  be99797  c4627883i   
10          0     0       0        0  ec32773  c1767347h   
11          0     0       0    north  be30668  e7076547h   
12          0     0       0    north  dc75761  d8806646g   
13          0     0  396358        0  de93468  c1820202h   
14          0     0  945108    south  ca88959  e1957315f   
15          0     0       0     east  bc29711  e2429135g   
16          0     0       0        0  cb65768  d7857259g   
17          0     0       0        0  da19591  c2348960g   
18          0     0       0    north  ea71828  e5639644g   
19          0     0  632579    north  bb73057  b7614014g   

                                               school     medicine_group  \
0                         Ramkrishna mission, Asansol                  0   
1   national gems higher secondary school, Kolkata...                  0   
2                        D.A.V public school, asansol                  0   
3                   Hemsheela Public School, Durgapur  antihypertensives   
4                    North point public school,Chanda                  0   
5                                 Delhi public school                  0   
6                    North point public school,Chanda  anti-inflammatory   
7         guru govind Singh public school, Chandigarh        antifungals   
8              Dhirubhai ambani public school, Mumbai       tranquilizer   
9                   Narayan group of schools, asansol                  0   
10                                Delhi public school        antifungals   
11  national gems higher secondary school, Kolkata...    antidepressants   
12                                St. Vincents school                  0   
13                  Hemsheela Public School, Durgapur           hormones   
14                       D.A.V public school, asansol                  0   
15                                St. Vincents school     antidiarrheals   
16                  Hemsheela Public School, Durgapur          laxatives   
17                  Burnpur Riverside School, Burnpur    antidepressants   
18                              Loreto convent school                  0   
19        guru govind Singh public school, Chandigarh        antibiotics   

   date_of_birth  
0      20:4:1994  
1      29:9:1959  
2      13:7:1970  
3      29:2:1993  
4              0  
5              0  
6      9:11:1982  
7     19:10:1984  
8       1:4:1952  
9              0  
10             0  
11     14:9:1971  
12    25:10:1953  
13             0  
14     11:2:1980  
15      2:4:1970  
16      5:4:1975  
17      1:7:1961  
18      6:1:1963  
19    25:11:1954

In [197]:
data.to_csv("sample_data3.csv")