In [26]:
import numpy as np
import pandas as pd
# import matplotlib as mpl
# import seaborn as sbs

y = np.random.randint(1,5,5)
y
coloumn = ['sl_no','acount_no','pin','ifsc','address','plot_no','pan_no','vter_no','school','college','stream','medical history','dob','profession','contact no','adiction']
len(coloumn)
sl_no = np.linspace(1,100,100,np.int64)
acount_no = np.random.normal(500000000,200000000,100)
acount_no = np.int64(acount_no)
a = np.random.randint(1,100,55)
a
for i in a:
    acount_no[i] = 000000000
acount_no



array([497968551,         0, 400263525,         0, 566350038,         0,
       206803972,         0, 648646614,         0, 809172683,         0,
               0, 588379875,         0, 502031651,         0,         0,
       537913794, 158303686, 600054827, 582001100,         0,         0,
       403977398, 276109703, 770198276, 465784418,         0,         0,
       884124893, 541474470, 570995746,         0,         0, 212639464,
               0, 100429027, 485523611, 556107699,         0,         0,
       700082184,         0,         0,         0, 743162242, 726491472,
       685666364,         0, 493075021, 488784604, 700864705, 304076737,
       240789310, 832299941, 814982722,         0, 365526082,   4482628,
               0, 442583869, 636656387, 675493162, 736824569, 564169896,
       610953971, 856962612,         0,         0, 541608236, 384254924,
       254628861, 429442463,         0, 360032261,         0, 136477231,
               0,         0,         0,         0, 

In [25]:
pin = np.random.normal(5000,2000,100)
pin = np.int64(pin)
b = np.random.randint(1,100,86)
b
for i in b:
    pin[i] = 000000000
pin

array([3514, 3320, 6187,    0, 3523,    0,    0,    0,    0, 6046, 3172,
       1677,    0, 7404, 6783, 2810, 4726, 4598, 5059, 4031, 5850,    0,
       5354, 2342, 7355,    0,    0, 8423,    0, 3904, 5023,    0,    0,
          0, 4683,    0,    0,    0,    0, 5652,    0, 2363, 7373, 6242,
          0,    0,    0, 2817, 4128, 4785,    0,    0,    0,    0, 3279,
          0,    0, 2720, 2910, 4682,    0,    0, 4126, 7503, 4506, 6277,
          0, 6652, 3983, 3421, 5378,    0, 2223, 5099, 5059,    0,    0,
       3728, 4374, 5163,    0,    0,    0,    0, 2393,    0,    0, 7763,
       4037, 6650,  374,    0, 3413, 2751,    0,    0,    0, 5753,    0,
          0])

In [53]:
rifsc = np.random.randint(000000,999999,20)
ifsc = np.zeros(100,np.int64)
ifsc
c = np.random.randint(1,100,40)
for i in c:
    if i>19:
        j = np.random.randint(0,20)
    else:
        j = i
    ifsc[i] = rifsc[j]
ifsc

array([     0, 660120,      0, 198615,      0,      0,      0,      0,
            0,      0, 215861, 636805,      0, 157510,      0,      0,
       897448,  19442,      0,      0, 421726,      0,      0,      0,
            0, 198615, 944560,      0, 198615,      0,      0, 157510,
       664218,      0,      0, 153639,      0, 897448,      0,      0,
       188457,      0,      0, 157510, 157510,      0, 944560, 260244,
            0,      0, 260244,      0,      0,      0,      0,      0,
       250483,      0,      0,      0,      0,      0,      0, 421726,
            0, 215861,      0,      0, 250483, 188457,      0, 664218,
            0,      0,      0, 221634,      0,      0,      0,      0,
            0,  19442, 421726,      0,      0,      0, 215861, 221634,
            0,      0,      0,      0,      0,      0,      0,      0,
            0,      0,      0,      0])

In [38]:
acount_no = pd.Series(acount_no)
pin = pd.Series(pin)
frame = {'acount_no':acount_no,'pin':pin,'ifsc':ifsc}
data = pd.DataFrame(frame)
data
data.to_excel("sample_data.xlsx")

In [76]:
address = {'1':'west','2':'south','3':'north','4':'east','5':'north_east','6':'north_west','7':'south_east','8':'south_west'}
address

{'1': 'west',
 '2': 'south',
 '3': 'north',
 '4': 'east',
 '5': 'north_east',
 '6': 'north_west',
 '7': 'south_east',
 '8': 'south_west'}

In [77]:
addresss = np.random.normal(4.5,1.5,8)
addresss = np.int64(addresss)
addresss


array([4, 4, 2, 3, 4, 3, 1, 2])

In [78]:
ad = np.zeros(100,np.int64)
ad
no = 75
i = 0
while i<no:
    ad[np.random.randint(0,99)] = addresss[np.random.randint(0,7)]
    i+=1
ad

array([0, 4, 0, 0, 0, 3, 0, 0, 0, 4, 2, 0, 1, 2, 3, 3, 4, 0, 0, 4, 0, 0,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 4, 2, 1, 1, 4, 0, 0, 0, 3, 0, 0, 3, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 1, 0, 3, 3, 3, 4, 3, 0, 3, 1, 2, 0,
       4, 0, 4, 2, 0, 0, 3, 4, 0, 0, 4, 0, 0, 2, 4, 0, 0, 3, 4, 1, 0, 3,
       4, 0, 2, 0, 3, 3, 4, 4, 1, 4, 4, 0])

In [92]:
l = []
for i in ad:
    if i == 0:
        l.append(0)
    else:
        l.append(address[str(i)])
l
# address['1']
location = pd.Series(l)
location


0        0
1     east
2        0
3        0
4        0
      ... 
95    east
96    west
97    east
98    east
99       0
Length: 100, dtype: object

In [95]:
data['location'] = location
data.to_excel("sampledata2.xlsx")
data

acount_no   pin    ifsc location
0   497968551  3514  699184        0
1           0  3320  800575     east
2   400263525  6187   57170        0
3           0     0  152109        0
4   566350038  3523       0        0
..        ...   ...     ...      ...
95  458832009     0       0     east
96  518087966     0  637694     west
97          0  5753       0     east
98  381346123     0       0     east
99          0     0  499313        0

[100 rows x 4 columns]

In [162]:
#pan
import random as r
alphabet = ['a','b','c','d','e','f']
# a = 
num = np.random.randint(10000,99999,5000)
num
pan = []
for i in range(5000):
    x = np.random.randint(0,5)
    y = np.random.randint(0,5)
    trans = alphabet[x]+alphabet[y]+str(num[i])
    pan.append(trans)
pan
# x = np.random.randint(0,5)
# x
pan = pd.Series(pan)
data['pan'] = pan
data.head()

acount_no   pin    ifsc location      pan      voter
0  497968551  3514  699184        0  bb56746  c1127113h
1          0  3320  800575     east  bb25135  a2242850i
2  400263525  6187   57170        0  ab82026  d2873882e
3          0     0  152109        0  ad78215  a6391058f
4  566350038  3523       0        0  cd23390  b5368892i

In [163]:
#voter
import random as r
alphabet1 = ['a','b','c','d','e','f']
alphabet2 = ['e','f','g','h','i','j','x']
# a = 
num = np.random.randint(1000000,9999999,5000)
num
voter = []
for i in range(5000):
    x = np.random.randint(0,5)
    y = np.random.randint(0,5)
    trans = alphabet1[x]+str(num[i])+alphabet2[y]
    voter.append(trans)
voter
# x = np.random.randint(0,5)
# x
voter = pd.Series(voter)
data['voter'] = voter
data.head()

acount_no   pin    ifsc location      pan      voter
0  497968551  3514  699184        0  bb56746  a7349058g
1          0  3320  800575     east  bb25135  c5463881g
2  400263525  6187   57170        0  ab82026  e4965359e
3          0     0  152109        0  ad78215  a2968341f
4  566350038  3523       0        0  cd23390  d3377069i

In [169]:
sch = ['D.A.V public school, asansol',
'D.A.V public school, Durgapur',
'Hemsheela Public School, Durgapur',
'Loreto convent school',
'La Martine boys school',
'Ramkrishna mission, Asansol',
'Delhi public school',
'Indira Gandhi girls school, Delhi',
'Dhirubhai ambani public school, Mumbai',
'St. Vincents school',
'St. Patricks school',
' Burnpur Riverside School, Burnpur',
' North point public school,Chanda',
 'Uma Rani gorai mohila Kalyan, Asansol',
 'national gems higher secondary school, Kolkata' 'AG Church , Sodepoore',
 'guru govind Singh public school, Chandigarh',
 'Narayan group of schools, asansol',
 'La Martine Boys, Kolkata',
'army school , shiliguri']
school = []
for i in range(5000):
    school.append(sch[np.random.randint(0,len(sch))])
school
school = pd.Series(school)
data['school'] = school
data.head()

acount_no   pin    ifsc location      pan      voter  \
0  497968551  3514  699184        0  bb56746  a7349058g   
1          0  3320  800575     east  bb25135  c5463881g   
2  400263525  6187   57170        0  ab82026  e4965359e   
3          0     0  152109        0  ad78215  a2968341f   
4  566350038  3523       0        0  cd23390  d3377069i   

                                   school  
0                  La Martine boys school  
1       Burnpur Riverside School, Burnpur  
2                  La Martine boys school  
3   Uma Rani gorai mohila Kalyan, Asansol  
4  Dhirubhai ambani public school, Mumbai

In [173]:

med = ['analgesics',
'antacids',
'antianxiety drugs',
'antiarrhythmics',
'antibacterial',
 'antibiotics',
'anticoagulant',
'thrombolytic',
'anticonvulsant',
' antidepressants',
 'antidiarrheals',
' antiemetics',
 'antifungals',
'antihypertensives',
 'anti-inflammatory',
 'antineoplastic',
 'antipsychotics',
 'antipyretics',
'antivirals',
 'barbiturates',
'beta-blockers',
 'bronchodilators',
'cold cures',
 'corticosteroids',
'cough suppressants',
 'cytotoxics',
 'decongestants',
 'diuretics',
 'expectorant',
'hormones',
'hypoglycemics',
'immunosuppressives',
'laxatives',
 'muscle relaxants',
'sedatives',
'sex hormones',
 'sleeping drugs',
'tranquilizer',
 'vitamins',]
med
medicine_group = []
fo11 ta medicine class
11 ta medicine class
11:06 pm
Drugs class-
1)analgesics
2)antacids
3) antianxiety drugs
4) antiarrhythmics
5) antibacterial
6) antibiotics
7) anticoagulant
8) thrombolytic
9) anticonvulsant
10) antidepressants
11) antidiarrheals
12) antiemetics
13) antifungals
14) antihistamines
15)antihypertensives
16) anti-inflammatory
17) antineoplastic
18) antipsychotics
19) antipyretics
20)antivirals
21) barbiturates
22)beta-blockers
23) bronchodilators
24)cold cures
25) corticosteroids
26)cough suppressants
27) cytotoxics
28) decongestants
29) diuretics
30) expectorant
31)hormones
32)hypoglycemics
33)immunosuppressives
34)laxatives
35) muscle relaxants
36)sedatives
37)sex hormones
38) sleeping drugs
39) tranquilizer
40) vitaminsr i in range(5000):
    medicine_group.append(med[np.random.randint(0,len(med))])
z = np.random.randint(0,5000,3000)
for i in z:
    medicine_group[i] = 0
    
medicine_group = pd.Series(medicine_group)

data['medicine_group'] = medicine_group
data.head()

acount_no   pin    ifsc location      pan      voter  \
0  497968551  3514  699184        0  bb56746  a7349058g   
1          0  3320  800575     east  bb25135  c5463881g   
2  400263525  6187   57170        0  ab82026  e4965359e   
3          0     0  152109        0  ad78215  a2968341f   
4  566350038  3523       0        0  cd23390  d3377069i   

                                   school     medicine_group  
0                  La Martine boys school  antianxiety drugs  
1       Burnpur Riverside School, Burnpur          laxatives  
2                  La Martine boys school                  0  
3   Uma Rani gorai mohila Kalyan, Asansol     anticonvulsant  
4  Dhirubhai ambani public school, Mumbai      decongestants

In [177]:
# dob
date = []
for i in range(5000):
    d = np.random.randint(1,31)
    m = np.random.randint(1,12)
    y = np.random.randint(1950,2000)
    date.append(str(d)+':'+str(m)+':'+str(y))
z = np.random.randint(0,5000,1790)
for i in z:
    date[i] = 0
dateofbirth = pd.Series(date)
data['date_of_birth'] = dateofbirth
data.head(20)

acount_no   pin    ifsc location      pan      voter  \
0   497968551  3514  699184        0  bb56746  a7349058g   
1           0  3320  800575     east  bb25135  c5463881g   
2   400263525  6187   57170        0  ab82026  e4965359e   
3           0     0  152109        0  ad78215  a2968341f   
4   566350038  3523       0        0  cd23390  d3377069i   
5           0     0  505488    north  aa33965  a6424938g   
6   206803972     0  704495        0  da71843  e2970274g   
7           0     0       0        0  ec41211  a6361870e   
8   648646614     0  517835        0  ce86338  a4600912h   
9           0  6046       0     east  ca79041  c9789510i   
10  809172683  3172       0    south  ae42641  c7768188h   
11          0  1677  267290        0  ac69659  c6822616h   
12          0     0       0     west  ce27526  c4189541h   
13  588379875  7404   12073    south  ae26590  b1772354h   
14          0  6783       0    north  ca51804  d3624005g   
15  502031651  2810  595521    north  de58063  d7532887h   
16          0  4726       0     east  dd56095  e4667849h   
17          0  4598  220011        0  ca53890  c7675860f   
18  537913794  5059       0        0  cd79061  c7040787h   
19  158303686  4031       0     east  ba12039  c3489479h   

                                               school      medicine_group  \
0                              La Martine boys school   antianxiety drugs   
1                   Burnpur Riverside School, Burnpur           laxatives   
2                              La Martine boys school                   0   
3               Uma Rani gorai mohila Kalyan, Asansol      anticonvulsant   
4              Dhirubhai ambani public school, Mumbai       decongestants   
5                              La Martine boys school        thrombolytic   
6                   Hemsheela Public School, Durgapur                   0   
7   national gems higher secondary school, Kolkata...                   0   
8                              La Martine boys school         antifungals   
9                            La Martine Boys, Kolkata           diuretics   
10                        Ramkrishna mission, Asansol                   0   
11        guru govind Singh public school, Chandigarh        antipyretics   
12             Dhirubhai ambani public school, Mumbai     bronchodilators   
13                        Ramkrishna mission, Asansol  immunosuppressives   
14                       D.A.V public school, asansol                   0   
15              Uma Rani gorai mohila Kalyan, Asansol                   0   
16                           La Martine Boys, Kolkata       decongestants   
17                  Burnpur Riverside School, Burnpur                   0   
18  national gems higher secondary school, Kolkata...        tranquilizer   
19                                St. Patricks school                   0   

   date_of_birth  
0              0  
1              0  
2      25:1:1997  
3       6:3:1958  
4      25:5:1971  
5     12:11:1970  
6              0  
7      28:4:1969  
8      26:3:1993  
9      23:8:1951  
10    28:10:1968  
11     15:7:1963  
12             0  
13     30:8:1950  
14             0  
15             0  
16     22:4:1953  
17      7:3:1967  
18      4:6:1956  
19      6:5:1965